### PR TITLE
Allow Symfony 6.4 LTS

### LINKED ISSUE #2: Accept Symfony 6.* (or 6.4 at least)
The `composer.json` file only accepts ^7.0 for symfony packages, is there a hard incompatibility for supporting earlier versions of Symfony, in particular the current LTS ?

### PR DESCRIPTION
**Pull request by danielburger1337**
Closes #2

### CODE REVIEW

**Comment by danielburger1337** [comment]
@florentdestremau This PR allows Symfony 6.4. 

The Unit tests pass, so there **shouldn't** be a problem since the test suite is quite comprehensive. 
I also created a brand new Symfony 6.4 application and everything worked out of the box.

I actually don't have any *real* Symfony 6.4 applications, so I would be gratefull if you could checkout the PR in your application and let me know if everything works correctly.

```bash
composer require danielburger1337/2fa-email@dev-symfony-lts
``` 

Otherwise this should be good to merge!

**Comment by florentdestremau** [comment]
We are currently implementing the 2FA, that's what prompted the issue in the first place. I will gladly report back in a couple of days, while we roll out and have a check

**Comment by florentdestremau** [comment]
The command doesn't install the branch:

```
$ composer require danielburger1337/2fa-email@dev-symfony-lts

In PackageDiscoveryTrait.php line 376:
                                                                                                                                                                                                                                                
  Could not find a matching version of package danielburger1337/2fa-email@dev-symfony-lts. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).  
                                                                                                                                                                                                                                                
```

**Comment by danielburger1337** [comment]
> The command doesn't install the branch:

A default composer.json does not allow installing dev branches.

https://getcomposer.org/doc/04-schema.md#minimum-stability

To circumvent this, temporarily add `"minimum-stability": "dev"` to your composer.json:

```json
{
    "name": "My Project",
    "minimum-stability": "dev",
    ...
}
```

---

Alternativly you can add the branch constraint to your composer.json manually and then run the following command:

```json
{
    "name": "My Project",
    "require": {
        "danielburger1337/2fa-email": "dev-symfony-lts",
        ...
    }
    ...
}
```

```bash
composer update danielburger1337/2fa-email -W
```

The `-W` means to update the package WITH its dependencies. Depending on your composer.lock, you either have to run the command with or without the flag (most likely you will need it).

**Comment by florentdestremau** [comment]
It's been working fine on our side for a week, looks good to me :+1:

**Comment by danielburger1337** [comment]
> It's been working fine on our side for a week, looks good to me 👍

Released as v1.1.0

Thank you very much for your suggestion and testing!

**Pull request merged**
